name: Daily Job Search Automation

on:
  schedule:
    - cron: "30 6 * * *"  # Runs every day at 12 PM IST (6:30 AM UTC)
  workflow_dispatch:      # Allows you to run manually too

jobs:
  run-search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run job search script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python daily_job_search_automation.py
